In [8]:
import numpy as np

In [9]:
array = np.array([[1,2] , [3,4] , [5,6]])
print(array, array.ndim)
print(0,1,2)



[[1 2]
 [3 4]
 [5 6]] 2
0 1 2


In [10]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c = np.array([a - b])
print( c )


[[4294967293 4294967293 4294967293]]


In [11]:
import numpy as np
arr1 = np.array([[ 1,2,3,3,4,5,56,4],[1,2,3,434,4,5,6,56665]])
print(arr1)


[[    1     2     3     3     4     5    56     4]
 [    1     2     3   434     4     5     6 56665]]


In [14]:
arr1 = np.array([[1,2],[43,54]])
arr2 = np.array([[9,8] , [2,3]])
arrconc = np.stack((arr1 , arr2)  , axis = 1)

print(arrconc)


[[[ 1  2]
  [ 9  8]]

 [[43 54]
  [ 2  3]]]


In [20]:
arr1 = np.array([[1,2],[43,54]])
arr2 = np.array([[9,8] , [2,3]])
arrconc = np.hstack((arr1 , arr2) )

print(arrconc)


[[ 1  2  9  8]
 [43 54  2  3]]


TypeError: 'numpy.ndarray' object is not callable